### PR TITLE
Create components as macros

### PR DESCRIPTION
**Pull request by gemmaleigh**
## What problem does the pull request solve?

This begins work on #13.

This PR:
- adds a button macro and a form-group macro
- shows how data can be passed to both macros, either via a data file or passed into the macro from the index page
- creates two variants of the button component and variants of the form-group component to show a form label and input, hint text and an error message.

I haven't moved the data for the form-group macro into separate files, as I think for now - it is much clearer to see how these work when this is passed in via the index page. That can happen as another PR later, as there is more work to create other variants of the form-group component.

## Screenshots (if appropriate):

initial components work

## What type of change is it?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by fofr** [comment]
What's a macro?

**Comment by dsingleton** [comment]
> What's a macro?

It's the nunjucks/jinja term for a re-usable template with arguments, equivalent to a ERB partial with local args. We don't intend to be tied to the nunjucks macros specifically, but using them as a general abstraction

Next we'll be looking at transpiling these macros to other templating languages, to try and make sure we stick to a common set of supported functionally.

**Comment by timpaul** [comment]
👍  to this. It'll be interesting to see how compatible this work is with Fractal's concept of components. Here's an example from our fractal prototype - [these files](https://github.com/alphagov/govuk_frontend_fractal_alpha/tree/master/components/forms/buttons) produce [this documentation](https://alphagov.github.io/govuk_frontend_fractal_alpha/components/detail/buttons.html).

**Comment by gemmaleigh** [comment]
Hi @timpaul, I was using [Fractal's docs on config files](http://fractal.build/guide/core-concepts/configuration-files) as a basis for this work, so the two should work well together. 

They recommend using a JavaScript file in the style of a CommonJS module that exports a configuration object _recommended as it offers a lot more flexibility_, so I went with that option.

The [button config file is here](https://github.com/alphagov/govuk_frontend_alpha/blob/master/app/data/button-primary.js). 
It doesn't have the option to make a link a button just yet, it's only a simple example.

If it differs from what Fractal expects, we should be able to transpile a config file in the format it requires from this starting point.

**Comment by timpaul** [comment]
You can specify the config files in Fractal as JSON rather than Yaml.

**Pull request merged**
