### PR TITLE
Add wrapper for the content block

### PR DESCRIPTION
**Pull request by gemmaleigh**
Add a wrapper to constrain the width of the content area.

Use the `id=“content”` here as the skiplink expects it

Use a wrapping class `.gv-o-wrapper`, to constrain the width of the page.

This has been [tested in the Node starter kit](https://github.com/alphagov/govuk-frontend-alpha-starter-kit-node/commit/55ffc5f171090f3c56c008f00bd4c6832549e328).

#### Before:
before
#### After:
after

#### What type of change is it?

- New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by dsingleton** [comment]
Happy with this as a default.

We discussed an opt-out for apps/pages that need to render full width content - I think that would still be useful, even in the alpha, what do you think?

**Comment by gemmaleigh** [comment]
I'm not sure how often full width content displayed in that area, but there's no harm in allowing the default to be overridden. 

I added an extra block `content_class`, this would give the option of adding a modifier class here to override the default width.

**Comment by dsingleton** [comment]
How about:

```
{% block content_wrapper %}
  <div id="content" class="gv-o-wrapper">
    {% block content %}{% endblock %}
  </div>
{% endblock %}
```

I think that gives the most flexibility. It allows the `#content` ID to be moved, as we get cases where the skip-target needs to be somewhere else. And avoids having the `content_class` block having to undo `gv-o-wrapper`.

That fits the common case with no additional config, but gives complete control for the complex case.

**Comment by gemmaleigh** [comment]
@dsingleton updated!

**Pull request merged**
